
import pandas as pd

# Dataset completo com dados limpos
dados = [
    # Anemia Falciforme (13 exemplos)
    ("cansaço extremo dor articular severa crises dolorosas mal estar geral", "anemia_falciforme"),
    ("cansaço extremo dor articular severa crises dolorosas", "anemia_falciforme"),
    ("cansaço extremo dor articular episódios dolorosos dor de cabeça", "anemia_falciforme"),
    ("cansaço severo dor articular crises de dor intensa", "anemia_falciforme"),
    ("cansaço severo dor articular intensa dor em crises", "anemia_falciforme"),
    ("fadiga severa dor nas juntas dor em episódios", "anemia_falciforme"),
    ("cansaço que não passa dor articular crises álgicas", "anemia_falciforme"),
    ("cansaço extremo dor articular severa crises dolorosas com fraqueza", "anemia_falciforme"),
    ("fadiga severa dor nas articulações crises de dor", "anemia_falciforme"),
    ("cansaço extremo dor articular episódios dolorosos", "anemia_falciforme"),
    ("cansaço severo dor articular intensa dor em crises", "anemia_falciforme"),
    ("fadiga constante dor nas juntas crises dolorosas", "anemia_falciforme"),
    ("cansaço que não passa dor articular crises álgicas com tontura", "anemia_falciforme"),
    
    # Artrite Reumatoide (15 exemplos)
    ("dor articular crônica juntas inchadas rigidez matinal", "artrite_reumatoide"),
    ("articulações inflamadas dor constante rigidez", "artrite_reumatoide"),
    ("dor nas juntas inchaço articular dificuldade de movimento com fraqueza", "artrite_reumatoide"),
    ("dor nas juntas inchaço articular dificuldade de movimento", "artrite_reumatoide"),
    ("dor nas articulações inchaço nas juntas rigidez matinal mal estar geral", "artrite_reumatoide"),
    ("dor nas juntas inchaço articular rigidez ao acordar dor de cabeça", "artrite_reumatoide"),
    ("dor nas juntas inchaço articular rigidez ao acordar", "artrite_reumatoide"),
    ("articulações inflamadas dor constante rigidez", "artrite_reumatoide"),
    ("articulações dolorosas inchaço persistente rigidez", "artrite_reumatoide"),
    ("dor articular juntas inchadas dificuldade para se mover", "artrite_reumatoide"),
    ("dor nas juntas inchaço articular rigidez ao acordar", "artrite_reumatoide"),
    ("dor nas juntas inchaço articular dificuldade de movimento perda de apetite", "artrite_reumatoide"),
    ("articulações rígidas e doloridas inchaço persistente", "artrite_reumatoide"),
    ("dor nas juntas inchaço articular rigidez ao acordar perda de apetite", "artrite_reumatoide"),
    ("dor articular juntas inchadas dificuldade para se mover com fraqueza", "artrite_reumatoide"),
    
    # Diabetes Tipo 1 (13 exemplos)
    ("sede constante micção frequente perda de peso rápida", "diabetes_tipo1"),
    ("muita sede urinar muito emagrecimento", "diabetes_tipo1"),
    ("sede excessiva poliúria perda de peso inexplicável", "diabetes_tipo1"),
    ("muita sede urina frequente emagrecimento súbito", "diabetes_tipo1"),
    ("sede excessiva urina frequente perda de peso mal estar geral", "diabetes_tipo1"),
    ("sede excessiva urina frequente perda de peso", "diabetes_tipo1"),
    ("sede intensa micção excessiva perda de peso mal estar geral", "diabetes_tipo1"),
    ("sede excessiva poliúria perda de peso inexplicável", "diabetes_tipo1"),
    ("sede constante urinar muito emagrecimento rápido", "diabetes_tipo1"),
    ("sede intensa urina em excesso emagrecimento súbito", "diabetes_tipo1"),
    ("sede constante urinar muito emagrecimento rápido com tontura", "diabetes_tipo1"),
    ("muita sede frequência urinária aumentada emagrecimento", "diabetes_tipo1"),
    ("muita sede urina frequente emagrecimento súbito perda de apetite", "diabetes_tipo1"),
    
    # Doença de Alzheimer (13 exemplos)
    ("esquecimento constante confusão perda de referências com fraqueza", "doenca_alzheimer"),
    ("esquecimento confusão perda de noção de tempo e lugar", "doenca_alzheimer"),
    ("esquecimento confusão perda de noção de tempo e lugar", "doenca_alzheimer"),
    ("perda de memória progressiva confusão dificuldade de orientação", "doenca_alzheimer"),
    ("problemas de memória confusão mental desorientação temporal", "doenca_alzheimer"),
    ("problemas de memória confusão mental desorientação temporal", "doenca_alzheimer"),
    ("problemas de memória confusão dificuldade de localização", "doenca_alzheimer"),
    ("perda de memória confusão mental desorientação", "doenca_alzheimer"),
    ("esquecimento constante confusão perda de referências com fraqueza", "doenca_alzheimer"),
    ("esquecimento constante confusão perda de referências", "doenca_alzheimer"),
    ("perda de memória confusão frequente dificuldade de localização", "doenca_alzheimer"),
    ("problemas de memória severos confusão mental desorientação", "doenca_alzheimer"),
    ("esquecimento frequente confusão perda de orientação", "doenca_alzheimer"),
    
    # Doença de Crohn (12 exemplos)
    ("cólicas abdominais intensas diarreia sanguinolenta", "doenca_crohn"),
    ("dor na região abdominal diarreia frequente fraqueza", "doenca_crohn"),
    ("cólicas fortes diarreia com muco emagrecimento perda de apetite", "doenca_crohn"),
    ("dor na região abdominal diarreia frequente fraqueza com tontura", "doenca_crohn"),
    ("dor abdominal severa diarreia crônica fadiga", "doenca_crohn"),
    ("dor no abdômen fezes líquidas perda de peso rápida", "doenca_crohn"),
    ("cólicas abdominais intensas diarreia sanguinolenta com fraqueza", "doenca_crohn"),
    ("dor abdominal severa diarreia crônica fadiga", "doenca_crohn"),
    ("cólicas fortes diarreia com muco emagrecimento com fraqueza", "doenca_crohn"),
    ("cólicas fortes diarreia com muco emagrecimento", "doenca_crohn"),
    ("cólicas abdominais diarreia persistente perda de apetite mal estar geral", "doenca_crohn"),
    ("dor na região abdominal diarreia frequente fraqueza dor de cabeça", "doenca_crohn"),
    
    # Doença de Lyme (14 exemplos)
    ("febre baixa cansaço dor no corpo manchas na pele", "doenca_lyme"),
    ("febre baixa cansaço constante dor no corpo manchas", "doenca_lyme"),
    ("febre baixa cansaço severo dor no corpo manchas cutâneas mal estar geral", "doenca_lyme"),
    ("febre baixa cansaço severo dor no corpo manchas cutâneas com tontura", "doenca_lyme"),
    ("febre baixa cansaço constante dor no corpo manchas perda de apetite", "doenca_lyme"),
    ("febre intermitente fadiga dor muscular erupção com tontura", "doenca_lyme"),
    ("febre baixa cansaço severo dor no corpo manchas cutâneas com tontura", "doenca_lyme"),
    ("febre persistente fadiga severa dor muscular erupções", "doenca_lyme"),
    ("febre fadiga dor muscular erupção cutânea com fraqueza", "doenca_lyme"),
    ("febre persistente fadiga severa dor muscular erupções", "doenca_lyme"),
    ("febre intermitente fadiga dor muscular erupção com tontura", "doenca_lyme"),
    ("febre intermitente cansaço dor corporal lesões cutâneas", "doenca_lyme"),
    ("febre fadiga dor muscular erupção cutânea mal estar geral", "doenca_lyme"),
    ("febre persistente fadiga severa dor muscular erupções com tontura", "doenca_lyme"),
    
    # Doença de Parkinson (13 exemplos)
    ("tremores nas mãos rigidez muscular movimentos lentos", "doenca_parkinson"),
    ("tremores nas extremidades rigidez lentidão motora dor de cabeça", "doenca_parkinson"),
    ("tremor nas mãos rigidez corporal bradicinesia", "doenca_parkinson"),
    ("tremor nas mãos rigidez muscular instabilidade postural", "doenca_parkinson"),
    ("tremor nas mãos rigidez corporal bradicinesia", "doenca_parkinson"),
    ("tremor característico músculos tensos movimentos lentos", "doenca_parkinson"),
    ("tremor de repouso rigidez movimentos prejudicados", "doenca_parkinson"),
    ("tremor característico músculos tensos movimentos lentos mal estar geral", "doenca_parkinson"),
    ("tremor de repouso rigidez movimentos prejudicados dor de cabeça", "doenca_parkinson"),
    ("tremores rigidez muscular perda de equilíbrio", "doenca_parkinson"),
    ("tremor de repouso rigidez movimentos prejudicados mal estar geral", "doenca_parkinson"),
    ("tremor em repouso rigidez dificuldade para se mover dor de cabeça", "doenca_parkinson"),
    ("tremor nas mãos rigidez muscular instabilidade postural dor de cabeça", "doenca_parkinson"),
    
    # Doença de Wilson (10 exemplos)
    ("cansaço dor na barriga tremor problemas no fígado", "doenca_wilson"),
    ("cansaço dor na região abdominal tremor hepatopatia", "doenca_wilson"),
    ("fadiga constante dor abdominal tremores hepatopatia", "doenca_wilson"),
    ("cansaço severo dor na barriga tremor disfunção hepática mal estar geral", "doenca_wilson"),
    ("cansaço severo dor na barriga tremor disfunção hepática", "doenca_wilson"),
    ("cansaço constante dor no abdômen tremor problemas hepáticos", "doenca_wilson"),
    ("fadiga dor abdominal tremores problemas hepáticos", "doenca_wilson"),
    ("cansaço crônica dor abdominal tremores disfunção do fígado", "doenca_wilson"),
    ("fadiga extrema dor abdominal tremores hepatopatia", "doenca_wilson"),
    ("cansaço constante dor no abdômen tremor problemas hepáticos com tontura", "doenca_wilson"),
    
    # Esclerose Lateral (11 exemplos)
    ("braços sem força fala difícil atrofia muscular", "esclerose_lateral"),
    ("braços fracos problemas na fala contrações musculares", "esclerose_lateral"),
    ("perda de força muscular dificuldade para engolir dor de cabeça", "esclerose_lateral"),
    ("dificuldade para levantar os braços fala alterada", "esclerose_lateral"),
    ("perda de força fala lenta rigidez muscular com fraqueza", "esclerose_lateral"),
    ("perda de força nos membros fala arrastada espasmos", "esclerose_lateral"),
    ("perda de força nos membros fala arrastada espasmos", "esclerose_lateral"),
    ("perda de força muscular dificuldade para engolir", "esclerose_lateral"),
    ("dificuldade para levantar os braços fala alterada", "esclerose_lateral"),
    ("perda de força nos membros fala arrastada espasmos perda de apetite", "esclerose_lateral"),
    ("dificuldade para mover os braços fala prejudicada tremores", "esclerose_lateral"),
    
    # Esclerose Múltipla (13 exemplos)
    ("fadiga persistente perda de força visão dupla formigamento com tontura", "esclerose_multipla"),
    ("fadiga crônica coordenação prejudicada visão turva", "esclerose_multipla"),
    ("fadiga fraqueza nas pernas visão turva formigamento", "esclerose_multipla"),
    ("cansaço severo fraqueza muscular visão dupla dormência", "esclerose_multipla"),
    ("cansaço severo fraqueza muscular problemas visuais tontura", "esclerose_multipla"),
    ("cansaço persistente perda de força visão dupla formigamento com tontura", "esclerose_multipla"),
    ("cansaço extremo pernas fracas visão embaçada formigamento", "esclerose_multipla"),
    ("fadiga persistente perda de força visão dupla formigamento dor de cabeça", "esclerose_multipla"),
    ("cansaço persistente perda de força visão dupla formigamento", "esclerose_multipla"),
    ("cansaço severo fraqueza muscular problemas visuais tontura com tontura", "esclerose_multipla"),
    ("fadiga persistente perda de força visão dupla formigamento", "esclerose_multipla"),
    ("fadiga crônica coordenação prejudicada visão turva", "esclerose_multipla"),
    ("fadiga perda de equilíbrio problemas de visão dormência", "esclerose_multipla"),
    
    # Febre Maculosa (13 exemplos)
    ("temperatura alta dor nos músculos cansaço que não passa", "febre_maculosa"),
    ("febre alta dor no corpo todo cansaço extremo", "febre_maculosa"),
    ("febre persistente dor muscular generalizada erupção cutânea", "febre_maculosa"),
    ("temperatura alta dor nos músculos cansaço que não passa", "febre_maculosa"),
    ("febre alta dor nas costas náusea vômito", "febre_maculosa"),
    ("temperatura elevada dores musculares intensas cansaço severo com fraqueza", "febre_maculosa"),
    ("temperatura elevada dor generalizada náusea", "febre_maculosa"),
    ("temperatura elevada dores musculares intensas fadiga severa com fraqueza", "febre_maculosa"),
    ("temperatura elevada dores musculares intensas fadiga severa", "febre_maculosa"),
    ("febre persistente fadiga extrema erupções na pele", "febre_maculosa"),
    ("temperatura alta dor nos músculos cansaço que não passa", "febre_maculosa"),
    ("dor de cabeça intensa febre alta dor muscular", "febre_maculosa"),
    ("febre persistente fadiga extrema erupções na pele", "febre_maculosa"),
    
    # Fibromialgia (13 exemplos)
    ("dor no corpo todo cansaço constante dificuldade para dormir", "fibromialgia"),
    ("dores musculares difusas fadiga severa sono ruim", "fibromialgia"),
    ("dor muscular difusa cansaço severo dificuldades do sono com tontura", "fibromialgia"),
    ("dor em múltiplos pontos fadiga crônica insônia severa", "fibromialgia"),
    ("dor corporal generalizada cansaço persistente sono fragmentado", "fibromialgia"),
    ("dor em vários pontos do corpo cansaço extremo insônia perda de apetite", "fibromialgia"),
    ("dor muscular generalizada fadiga crônica insônia perda de apetite", "fibromialgia"),
    ("dor generalizada cansaço que não melhora problemas para dormir", "fibromialgia"),
    ("dor muscular generalizada cansaço crônica insônia", "fibromialgia"),
    ("dor muscular generalizada fadiga crônica insônia com tontura", "fibromialgia"),
    ("dor no corpo todo cansaço constante dificuldade para dormir perda de apetite", "fibromialgia"),
    ("dor muscular difusa cansaço severo dificuldades do sono dor de cabeça", "fibromialgia"),
    ("dor no corpo todo cansaço constante dificuldade para dormir com tontura", "fibromialgia"),
    
    # Hipertireoidismo (13 exemplos)
    ("emagrecimento rápido taquicardia ansiedade constante mal estar geral", "hipertireoidismo"),
    ("perda de peso palpitações frequentes nervosismo", "hipertireoidismo"),
    ("emagrecimento súbito batimentos acelerados ansiedade", "hipertireoidismo"),
    ("emagrecimento rápido taquicardia ansiedade constante dor de cabeça", "hipertireoidismo"),
    ("emagrecimento palpitações estado de nervosismo", "hipertireoidismo"),
    ("perda de peso inexplicável coração acelerado agitação", "hipertireoidismo"),
    ("emagrecimento súbito coração disparado ansiedade com tontura", "hipertireoidismo"),
    ("perda de peso inexplicável coração acelerado agitação mal estar geral", "hipertireoidismo"),
    ("emagrecimento súbito coração disparado ansiedade", "hipertireoidismo"),
    ("emagrecimento palpitações estado de nervosismo mal estar geral", "hipertireoidismo"),
    ("emagrecimento rápido taquicardia ansiedade constante", "hipertireoidismo"),
    ("perda de peso rápida batimentos irregulares agitação", "hipertireoidismo"),
    ("perda de peso palpitações frequentes nervosismo perda de apetite", "hipertireoidismo"),
    
    # Hipotireoidismo (14 exemplos)
    ("fadiga severa obesidade frieza excessiva", "hipotireoidismo"),
    ("cansaço extremo obesidade progressiva sensação de frio", "hipotireoidismo"),
    ("cansaço severo aumento de peso frio excessivo com tontura", "hipotireoidismo"),
    ("cansaço crônica aumento de peso inexplicável intolerância ao frio", "hipotireoidismo"),
    ("cansaço extremo ganho de peso inexplicável sensibilidade ao frio", "hipotireoidismo"),
    ("cansaço que não passa ganho de peso rápido frio constante dor de cabeça", "hipotireoidismo"),
    ("cansaço extremo ganho de peso inexplicável sensibilidade ao frio dor de cabeça", "hipotireoidismo"),
    ("fadiga constante obesidade intolerância ao frio", "hipotireoidismo"),
    ("fadiga crônica aumento de peso inexplicável intolerância ao frio com tontura", "hipotireoidismo"),
    ("fadiga constante obesidade intolerância ao frio dor de cabeça", "hipotireoidismo"),
    ("cansaço severo aumento de peso frio excessivo com tontura", "hipotireoidismo"),
    ("cansaço extremo ganho de peso inexplicável sensibilidade ao frio perda de apetite", "hipotireoidismo"),
    ("cansaço constante aumento de peso sensibilidade ao frio", "hipotireoidismo"),
    ("fadiga crônica aumento de peso inexplicável intolerância ao frio", "hipotireoidismo"),
    
    # Lúpus (13 exemplos)
    ("dor articular fadiga crônica sensibilidade ao sol com fraqueza", "lupus"),
    ("juntas doloridas cansaço que não passa manchas na face", "lupus"),
    ("dor articular fadiga crônica sensibilidade ao sol", "lupus"),
    ("dor nas articulações cansaço extremo problemas de pele", "lupus"),
    ("dor nas juntas fadiga que não melhora erupção facial", "lupus"),
    ("dor articular fadiga crônica sensibilidade ao sol mal estar geral", "lupus"),
    ("fadiga constante dor nas articulações sensibilidade à luz", "lupus"),
    ("dor articular generalizada fadiga severa erupções cutâneas", "lupus"),
    ("articulações rígidas cansaço constante fotossensibilidade", "lupus"),
    ("dor nas juntas fadiga que não melhora erupção facial com fraqueza", "lupus"),
    ("cansaço extremo articulações inchadas fotofobia", "lupus"),
    ("articulações rígidas cansaço constante fotossensibilidade perda de apetite", "lupus"),
    ("dor articular generalizada fadiga severa erupções cutâneas", "lupus"),
    
    # Miastenia Gravis (13 exemplos)
    ("perda de força cansaço diplopia problemas de deglutição", "miastenia_gravis"),
    ("perda de força cansaço extremo diplopia problemas para engolir", "miastenia_gravis"),
    ("fraqueza muscular fadiga severa visão dupla dificuldade para engolir", "miastenia_gravis"),
    ("perda de força cansaço diplopia problemas para engolir", "miastenia_gravis"),
    ("perda de força muscular cansaço problemas visuais dificuldade de deglutição perda de apetite", "miastenia_gravis"),
    ("fraqueza nos músculos fadiga severa visão dupla disfagia com fraqueza", "miastenia_gravis"),
    ("perda de força cansaço diplopia problemas para engolir", "miastenia_gravis"),
    ("fraqueza nos músculos fadiga constante visão dupla dificuldade de deglutição", "miastenia_gravis"),
    ("perda de força cansaço diplopia problemas de deglutição", "miastenia_gravis"),
    ("fraqueza muscular fadiga visão dupla dificuldade para engolir com tontura", "miastenia_gravis"),
    ("perda de força muscular cansaço problemas visuais dificuldade de deglutição com fraqueza", "miastenia_gravis"),
    ("perda de força muscular cansaço problemas visuais dificuldade de deglutição com fraqueza", "miastenia_gravis"),
    ("perda de força muscular cansaço problemas visuais dificuldade de deglutição", "miastenia_gravis"),
    
    # Porfiria (12 exemplos)
    ("dor intensa na barriga enjoo vômito confusão perda de apetite", "porfiria"),
    ("dor abdominal intensa náusea persistente vômito confusão mental com fraqueza", "porfiria"),
    ("dor abdominal severa enjoo vômito confusão mental", "porfiria"),
    ("dor abdominal severa náusea vômito confusão mental com tontura", "porfiria"),
    ("dor severa na barriga enjoo vômito persistente confusão", "porfiria"),
    ("dor abdominal severa náusea vômito confusão mental", "porfiria"),
    ("dor severa na barriga enjoo vômito frequente alterações cognitivas", "porfiria"),
    ("dor forte no abdômen enjoo constante vômito confusão", "porfiria"),
    ("dor severa na barriga enjoo vômito frequente alterações cognitivas perda de apetite", "porfiria"),
    ("dor intensa no abdômen enjoo severo vômito confusão perda de apetite", "porfiria"),
    ("dor abdominal aguda enjoo vômito confusão mental mal estar geral", "porfiria"),
    ("dor abdominal forte náusea constante vômito alterações mentais", "porfiria"),
    
    # Sarcoidose (14 exemplos)
    ("cansaço severo falta de ar aos esforços tosse febre", "sarcoidose"),
    ("cansaço crônica falta de ar tosse seca persistente febre mal estar geral", "sarcoidose"),
    ("cansaço extremo falta de ar tosse persistente febre baixa", "sarcoidose"),
    ("cansaço dispneia aos esforços tosse febre baixa", "sarcoidose"),
    ("fadiga constante dispneia tosse seca febre intermitente dor de cabeça", "sarcoidose"),
    ("fadiga falta de ar tosse seca febre baixa", "sarcoidose"),
    ("cansaço constante dificuldade para respirar tosse febre intermitente", "sarcoidose"),
    ("fadiga severa dificuldade respiratória tosse seca febre mal estar geral", "sarcoidose"),
    ("cansaço severo falta de ar aos esforços tosse febre dor de cabeça", "sarcoidose"),
    ("cansaço severo falta de ar aos esforços tosse febre", "sarcoidose"),
    ("cansaço dificuldade para respirar tosse febre", "sarcoidose"),
    ("fadiga crônica falta de ar tosse seca persistente febre com fraqueza", "sarcoidose"),
    ("fadiga constante dispneia tosse seca febre intermitente", "sarcoidose"),
    ("cansaço dispneia aos esforços tosse febre baixa dor de cabeça", "sarcoidose"),
    
    # Síndrome da Fadiga Crônica (13 exemplos)
    ("fadiga severa crônica dor no corpo todo problemas de foco", "sindrome_fadiga_cronica"),
    ("cansaço que não alivia dor muscular difusa névoa cerebral", "sindrome_fadiga_cronica"),
    ("fadiga extrema constante dor generalizada dificuldade mental", "sindrome_fadiga_cronica"),
    ("fadiga severa crônica dor no corpo todo problemas de foco dor de cabeça", "sindrome_fadiga_cronica"),
    ("cansaço que não alivia dor muscular difusa névoa cerebral", "sindrome_fadiga_cronica"),
    ("cansaço constante e severo dores musculares problemas cognitivos", "sindrome_fadiga_cronica"),
    ("cansaço severo crônica dor no corpo todo problemas de foco", "sindrome_fadiga_cronica"),
    ("cansaço extremo que não melhora dor muscular problemas de memória perda de apetite", "sindrome_fadiga_cronica"),
    ("fadiga extrema dor generalizada dificuldade de concentração", "sindrome_fadiga_cronica"),
    ("fadiga extrema dor generalizada dificuldade de concentração com fraqueza", "sindrome_fadiga_cronica"),
    ("cansaço extremo e persistente dor muscular confusão", "sindrome_fadiga_cronica"),
    ("cansaço extremo e persistente dor muscular confusão", "sindrome_fadiga_cronica"),
    ("cansaço constante e severo dores musculares problemas cognitivos", "sindrome_fadiga_cronica"),
    
    # Síndrome de Sjögren (11 exemplos)
    ("secura na boca olhos ressecados cansaço dor articular crônica com fraqueza", "sindrome_sjogren"),
    ("boca seca olhos secos severos fadiga dor nas articulações", "sindrome_sjogren"),
    ("secura oral olhos ressecados cansaço constante dor articular dor de cabeça", "sindrome_sjogren"),
    ("secura oral olhos ressecados cansaço constante dor articular", "sindrome_sjogren"),
    ("boca ressecada olhos secos crônicos fadiga dor articular dor de cabeça", "sindrome_sjogren"),
    ("boca ressecada olhos secos fadiga constante dor articular", "sindrome_sjogren"),
    ("boca seca persistente olhos secos fadiga dor articular", "sindrome_sjogren"),
    ("secura na boca olhos ressecados cansaço extremo dor nas juntas", "sindrome_sjogren"),
    ("boca seca olhos secos fadiga dor articular perda de apetite", "sindrome_sjogren"),
    ("secura oral olhos ressecados cansaço constante dor articular", "sindrome_sjogren"),
    ("boca ressecada olhos secos crônicos cansaço dor articular", "sindrome_sjogren"),
]

# criar uma funcao e colocar os dados acima em um DataFrame do pandas
def dataset_completo():
    df = pd.DataFrame(dados, columns=["sintomas", "diagnostico"])
    return df